# -*- coding: utf-8 -*-
"""Límites y algo más

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GI_C3BSTsmqz3V8v1HCPMHhxQbt4GAC1
"""

import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(-12, 12, 400)
y = x**2

a = 6
a2= a**2
ks = [25, 49]

fig, axs = plt.subplots(3, 2, figsize=(12, 10))
fig.suptitle('|x^2 - 6^2| comparado con 25 y 49', fontsize=16)

def shade_intervals(ax, intervals, color, label):
  for inter in intervals:
    if np.isfinite(inter[0]) and np.isfinite(inter[1]):
      ax.axvspan(inter[0], inter[1], alpha=0.3, color=color, label=label)
    elif np.isneginf(inter[0]):
      ax.axvspan(-12, inter[1], alpha = 0.3, color=color, label=label)
    elif np.isposinf(inter[1]):
      ax.axvspan(inter[0], 12, alpha = 0.3, color=color, label=label)

for i, k in enumerate(ks):

  sols_eq = []
  if 36 - k > 0:
    sols_eq += [-np.sqrt(36-k), np.sqrt(36-k)]
  sols_eq += [-np.sqrt(36+k), np.sqrt(36+k)]

  lower = max(0, 36-k)
  upper = 36 + k
  sols_lt = []
  if 36-k > 0:
    sols_lt += [(-np.sqrt(upper), np.sqrt(lower)), (-np.sqrt(lower), np.sqrt(upper))]
  else:
    sols_lt =  [(-np.sqrt(upper), np.sqrt(upper))]

  sols_gt = []
  if 36 - k > 0:
    sols_gt = [(-np.inf, -np.sqrt(36+k)), (-np.sqrt(36-k), np.sqrt(36-k)), (np.sqrt(36+k), np.inf)]
  else:
    sols_gt = [(-np.inf, -np.sqrt(36+k)), (np.sqrt(36+k), np.inf)]

  ax_lt = axs[0,i]
  ax_lt.set_title(f'|x^2 - 36| < {k}')
  shade_intervals(ax_lt, sols_lt, 'green', 'Solución')
  ax_lt.axhline(0, color='black', linewidth=0.8)
  ax_lt.set_xlim(-12, 12)
  ax_lt.set_ylim(-0.5, 0.5)
  ax_lt.legend()

  ax_gt = axs[1,i]
  ax_gt.set_title(f'|x^2 - 36| > {k}')
  shade_intervals(ax_gt, sols_gt, 'orange', 'Solución')
  ax_gt.axhline(0, color='black', linewidth=0.8)
  ax_gt.set_xlim(-12, 12)
  ax_gt.set_ylim(-0.5, 0.5)
  ax_gt.legend()

  ax_eq = axs[2,i]
  ax_eq.set_title(f'|x^2 - 36| = {k}')
  for s in sols_eq:
    ax_eq.plot(s, 0, 'ro', label='Solución' if s == sols_eq[0] else "")
  ax_eq.axhline(0, color='black', linewidth=0.8)
  ax_eq.set_xlim(-12, 12)
  ax_eq.set_ylim(-0.5, 0.5)
  ax_eq.legend()

plt.tight_layout()
plt.show()

import numpy as np
import matplotlib.pyplot as plt

x1 = np.linspace(-10, 10, 1000)
y1 = np.sinc(x1 / np.pi)

x2 = np.linspace(0.001, 10, 1000)
y2 = np.sin(x2) / np.sqrt(x2)

x3 = np.linspace(-2, -0.001, 500)
x3b = np.linspace(0.001, 2, 500)
y3 = np.sin(x3) / (x3**2)
y3b = np.sin(x3b) / (x3b**2)

plt.figure(figsize=(8, 12))

plt.subplot(3, 1, 1)
plt.plot(x1, y1, label=r'$f(x)=\frac{\sin x}{x}$')
plt.axhline(1, color='gray', linestyle='--', linewidth=1)
plt.title(r'$f(x)=\frac{\sin x}{x}$')
plt.ylim(-0.5, 1.5)
plt.grid(True)
plt.legend

plt.subplot(3, 1, 2)
plt.plot(x2, y2, color='orange', label=r'$\frac{\sin x}{\sqrt{x}}$')
plt.axhline(1, color='gray', linestyle='--', linewidth=1)
plt.title(r'$f(x)=\frac{\sin x}{\sqrt{x}}$')
plt.ylim(-2, 2)
plt.grid(True)
plt.legend

plt.subplot(3, 1, 3)
plt.plot(x3, y3, color='green', label=r'$\frac{\sin x}{x^2}$')
plt.plot(x3b, y3b, color='green')
plt.axvline(0, color='gray', linestyle='--', linewidth=1)
plt.title(r'$f(x)=\frac{\sin x}{x^2}$')
plt.ylim(-50, 50)
plt.grid(True)
plt.legend()

plt.tight_layout()
plt.show()

import numpy as np
import matplotlib.pyplot as plt

v_e = 1
g = 9.8

t = np.linspace(0, 1, 500)

v = v_e * (1 - np.exp(-g * t/ v_e))

v_99 = 0.99 * v_e

plt.figure(figsize=(8,5))
plt.plot(t, v, label='v(t) = v_e(1 - exp(-g t / v_e))', color='blue')
plt.axhline(y=v_99, color='red', linestyle='--', label='99% v_e')
plt.xlabel('Tiempo (s)')
plt.ylabel('Velocidad (m/s)')
plt.title('Velocidad de una gota de lluevia vs. Tiempo')
plt.legend()
plt.grid(True)
plt.show()